# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!
target 'MobileClient' do
pod 'Charts'
end

target 'MobileClientTests' do

end

target 'MobileClientUITests' do

end
